package httpapi

const appJS = `(function(){
'use strict';
const root=document.querySelector('#app');
const csrf=()=>sessionStorage.getItem('csrf')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>{const n=Number(v||0);return Number.isFinite(n)?n.toLocaleString('id-ID'):esc(v)};
const date=v=>v?new Date(v).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'-';
const statusLabel={menunggu_unit:'Menunggu Verifikasi Unit',menunggu_dinas:'Menunggu Verifikasi Dinas',menunggu_tte:'Menunggu TTE Pimpinan',dikembalikan_unit:'Dikembalikan Unit',dikembalikan_dinas:'Dikembalikan Dinas',terbit:'Surat Terbit'};
const statusClass=s=>s==='terbit'?'green':(s||'').startsWith('dikembalikan')?'red':s==='menunggu_tte'?'purple':'';
async function api(path,opt={}){const o={credentials:'same-origin',...opt,headers:{...(opt.headers||{})}};if(o.body&&!(o.body instanceof FormData)){o.headers['Content-Type']='application/json'}if(o.method&&o.method!=='GET'){o.headers['X-CSRF-Token']=csrf()}const r=await fetch(path,o);let x={};try{x=await r.json()}catch(_){}if(r.status===401){location.href='/login';throw new Error('Sesi berakhir')}if(!r.ok)throw new Error(x.error?.message||'Permintaan gagal');return x.data}
function shell(title,subtitle,body){root.innerHTML='<div class="app-head"><div><p class="eyebrow">SI CENDIKIA</p><h1>'+esc(title)+'</h1><p class="muted">'+esc(subtitle||'')+'</p></div><div class="toolbar"><button id="refresh" class="button button-ghost">Muat ulang</button><button id="logout" class="button button-small">Keluar</button></div></div><div id="flash"></div>'+body;document.querySelector('#logout').onclick=async()=>{try{await api('/api/v1/auth/logout',{method:'POST'});sessionStorage.clear();location.href='/'}catch(e){flash(e.message)}};document.querySelector('#refresh').onclick=()=>location.reload()}
function flash(msg,ok=false){const e=document.querySelector('#flash');if(e)e.innerHTML='<div class="alert '+(ok?'success':'')+'">'+esc(msg)+'</div>'}
function badge(s){return '<span class="badge '+statusClass(s)+'">'+esc(statusLabel[s]||s)+'</span>'}
function submissionCard(s){return '<article class="card panel"><div class="app-head"><div><strong>Pengajuan #'+esc(s.id)+'</strong><p class="muted">Diajukan '+date(s.submitted_at)+' · TMT '+date(s.proposed_tmt)+'</p></div>'+badge(s.status)+'</div><div class="two-col"><div><p><b>'+esc(s.teacher_name)+'</b><br>NIP '+esc(s.nip)+' · '+esc(s.unit_name)+'</p><p>Gaji: <b>Rp '+money(s.current_salary)+'</b> → <b>Rp '+money(s.next_salary)+'</b></p></div><div class="toolbar"><button class="button button-ghost detail" data-id="'+s.id+'">Lihat detail</button>'+(s.letter?'<a class="button button-success" href="/api/v1/letters/'+s.letter.id+'/download">Unduh surat</a>':'')+'</div></div></article>'}
async function loadASN(me){let items=await api('/api/v1/submissions');const teacher=me.teacher||{};shell('Dasbor Guru',me.name+' · '+(teacher.nip||me.username),'<div class="grid grid-3"><div class="card"><h2>Data ASN</h2><p>'+esc(teacher.asn_type||'-').toUpperCase()+' · '+esc(teacher.pangkat_gol||'-')+'<br>Masa kerja '+esc(teacher.masa_kerja_tahun||'-')+' tahun<br>'+esc(teacher.unit||me.unit||'-')+'</p></div><div class="card"><h2>Gaji sekarang</h2><p class="stat">Rp '+money(teacher.gaji_sekarang)+'</p></div><div class="card"><h2>Gaji berikutnya</h2><p class="stat">Rp '+money(teacher.gaji_berikutnya)+'</p></div></div><div class="card panel"><h2>Ajukan KGB Baru</h2><p class="muted">Jika data masa kerja atau TMT KGB terakhir belum tersedia, lengkapi berdasarkan dokumen resmi dan sertakan dalam PDF pendukung.</p><form id="submission-form" class="two-col"><label>Usulan TMT KGB<input required type="date" name="proposed_tmt"></label><label>Masa kerja tahun<input required min="0" step="1" type="number" name="masa_kerja_tahun" value="'+esc(teacher.masa_kerja_tahun||'')+'"></label><label>TMT KGB terakhir<input type="date" name="tmt_kgb_last" value="'+esc(teacher.tmt_kgb_last||'')+'"></label><label>Berkas PDF maksimal 5MB<input required type="file" name="file" accept="application/pdf"></label><div><button class="button" type="submit">Kirim pengajuan</button></div></form></div><section><h2>Riwayat Pengajuan</h2><div id="submission-list">'+(items.length?items.map(submissionCard).join(''):'<div class="card muted">Belum ada pengajuan.</div>')+'</div></section>');document.querySelector('#submission-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const data=new FormData(f);try{await api('/api/v1/submissions',{method:'POST',body:data});flash('Pengajuan berhasil dikirim.',true);setTimeout(()=>location.reload(),500)}catch(err){flash(err.message)}};document.querySelectorAll('.detail').forEach(b=>b.onclick=()=>showSubmission(b.dataset.id));}
async function showSubmission(id){try{const x=await api('/api/v1/submissions/'+id);const s=x.submission;const history=x.history||[];root.innerHTML='<button class="button button-ghost" onclick="location.reload()">← Kembali</button><div class="card panel"><div class="app-head"><div><h1>Pengajuan #'+s.id+'</h1><p>'+esc(s.teacher_name)+' · '+esc(s.nip)+'</p></div>'+badge(s.status)+'</div><p>TMT usulan: '+date(s.proposed_tmt)+'</p><p>Gaji: Rp '+money(s.current_salary)+' → Rp '+money(s.next_salary)+'</p><p><a class="button button-ghost" href="/api/v1/submissions/'+s.id+'/file">Lihat berkas PDF</a>'+(s.letter?'<a class="button button-success" href="/api/v1/letters/'+s.letter.id+'/download">Unduh surat terbit</a>':'')+'</p><h2>Timeline</h2><div class="timeline">'+history.map(a=>'<div class="timeline-item"><b>'+esc(a.action)+'</b><br><span class="muted">'+date(a.created_at)+' · '+esc(a.actor_name||'Sistem')+'</span>'+(a.details?.note?'<p>'+esc(a.details.note)+'</p>':'')+'</div>').join('')+'</div></div>'}catch(e){flash(e.message)}}
async function loadQueue(me){const role=me.role;const path=role==='verifikator_unit'?'/api/v1/verifications/unit':(role==='verifikator_dinas'||role==='admin_dinas')?'/api/v1/verifications/dinas':'/api/v1/letters/pending-tte';const items=await api(path);const title=role==='verifikator_unit'?'Antrean Verifikasi Unit':(role==='verifikator_dinas'||role==='admin_dinas')?'Antrean Verifikasi Dinas':'Antrean TTE Pimpinan';shell(title,me.name+(me.unit?' · '+me.unit:''),'<div id="queue">'+(items.length?items.map(submissionCard).join(''):'<div class="card muted">Tidak ada pengajuan dalam antrean.</div>')+'</div>');document.querySelectorAll('.detail').forEach(b=>b.onclick=()=>review(items.find(x=>String(x.id)===b.dataset.id),role));}
async function review(s,role){root.innerHTML='<button class="button button-ghost" onclick="location.reload()">← Kembali</button><div class="card panel"><div class="app-head"><div><p class="eyebrow">Pemeriksaan #'+s.id+'</p><h1>'+esc(s.teacher_name)+'</h1><p>'+esc(s.nip)+' · '+esc(s.unit_name)+'</p></div>'+badge(s.status)+'</div><div class="two-col"><div><p>Pangkat/golongan: '+esc(s.pangkat_gol)+'<br>Masa kerja: '+esc(s.masa_kerja_tahun)+' tahun</p><p>Gaji: Rp '+money(s.current_salary)+' → Rp '+money(s.next_salary)+'</p></div><div><a class="button button-ghost" href="/api/v1/submissions/'+s.id+'/file">Buka PDF berkas</a></div></div><label>Catatan keputusan<textarea id="note" placeholder="Wajib saat menolak"></textarea></label><div class="toolbar"><button id="approve" class="button button-success">'+(role==='pimpinan'?'Tanda tangani & terbitkan':'Setujui & teruskan')+'</button><button id="reject" class="button button-danger">Tolak</button></div><p id="review-error" class="error"></p></div>';if(role==='pimpinan'){document.querySelector('#approve').onclick=async()=>{const pass=prompt('Masukkan passphrase eSign pimpinan:');if(!pass)return;try{await api('/api/v1/letters/'+s.id+'/sign',{method:'POST',body:JSON.stringify({passphrase:pass})});flash('Surat berhasil diterbitkan.',true);setTimeout(()=>location.reload(),600)}catch(e){document.querySelector('#review-error').textContent=e.message}}}else{const prefix=role==='verifikator_unit'?'/api/v1/verifications/unit/':'/api/v1/verifications/dinas/';const stage=role==='verifikator_unit'?'menunggu_unit':'menunggu_dinas';document.querySelector('#approve').onclick=async()=>{try{await api(prefix+s.id+'/approve',{method:'POST',body:JSON.stringify({note:document.querySelector('#note').value})});location.reload()}catch(e){document.querySelector('#review-error').textContent=e.message}};document.querySelector('#reject').onclick=async()=>{const note=document.querySelector('#note').value.trim();if(!note){document.querySelector('#review-error').textContent='Catatan penolakan wajib diisi.';return}try{await api(prefix+s.id+'/reject',{method:'POST',body:JSON.stringify({note})});location.reload()}catch(e){document.querySelector('#review-error').textContent=e.message}}}}
async function loadAdmin(me){shell('Administrasi',me.name,'<div class="grid grid-3"><div class="card"><h2>Master guru</h2><button class="button button-ghost" id="teachers">Lihat master</button></div><div class="card"><h2>Pengguna</h2><button class="button button-ghost" id="users">Lihat pengguna</button></div><div class="card"><h2>Audit</h2><button class="button button-ghost" id="audit">Lihat audit</button></div></div><div class="card panel"><h2>Impor data</h2><p class="muted">Format CSV atau XLSX sesuai kolom pada dokumentasi.</p><form id="bkn-form"><label>File BKN<input required type="file" name="file" accept=".csv,.xlsx"></label><button class="button" type="submit">Impor BKN</button></form><p id="admin-msg"></p></div><div id="admin-result"></div>');document.querySelector('#bkn-form').onsubmit=async e=>{e.preventDefault();try{const x=await api('/api/v1/admin/import-bkn',{method:'POST',body:new FormData(e.currentTarget)});document.querySelector('#admin-msg').textContent='Impor selesai: '+x.rows_created+' dibuat, '+x.rows_updated+' diperbarui, '+x.rows_skipped+' dilewati.'}catch(err){document.querySelector('#admin-msg').textContent=err.message}};document.querySelector('#teachers').onclick=async()=>{const x=await api('/api/v1/admin/teachers');document.querySelector('#admin-result').innerHTML='<div class="card table-wrap"><h2>Master guru</h2><table class="table"><tr><th>NIP</th><th>Nama</th><th>ASN</th><th>Unit</th></tr>'+x.map(t=>'<tr><td>'+esc(t.nip)+'</td><td>'+esc(t.name)+'</td><td>'+esc(t.asn_type)+'</td><td>'+esc(t.unit_name)+'</td></tr>').join('')+'</table></div>'};document.querySelector('#users').onclick=async()=>{const x=await api('/api/v1/admin/users');document.querySelector('#admin-result').innerHTML='<div class="card table-wrap"><h2>Pengguna</h2><table class="table"><tr><th>Username</th><th>Nama</th><th>Role</th><th>Aktif</th></tr>'+x.map(u=>'<tr><td>'+esc(u.username)+'</td><td>'+esc(u.name)+'</td><td>'+esc(u.role)+'</td><td>'+u.is_active+'</td></tr>').join('')+'</table></div>'};document.querySelector('#audit').onclick=async()=>{const x=await api('/api/v1/admin/audit-logs');document.querySelector('#admin-result').innerHTML='<div class="card table-wrap"><h2>Audit terbaru</h2><table class="table"><tr><th>Waktu</th><th>Aksi</th><th>Aktor</th></tr>'+x.map(a=>'<tr><td>'+date(a.created_at)+'</td><td>'+esc(a.action)+'</td><td>'+esc(a.actor_name)+'</td></tr>').join('')+'</table></div>'}}
(async()=>{try{const me=await api('/api/v1/me');if(me.role==='asn')return loadASN(me);if(['verifikator_unit','verifikator_dinas','admin_dinas','pimpinan'].includes(me.role))return loadQueue(me);if(me.role==='admin')return loadAdmin(me);shell('Aplikasi',me.name,'<div class="card">Peran belum memiliki tampilan.</div>')}catch(e){root.innerHTML='<div class="card"><h1>Sesi diperlukan</h1><p>'+esc(e.message)+'</p><a class="button" href="/login">Masuk</a></div>'}})();
})();
`
